# i3 config file (v4)

# Keyboard
exec --no-startup-id xset r rate 250 50
exec --no-startup-id sh -c "xset r rate 250 50"

# Disable monitor power off and screensavers
exec --no-startup-id sh -c "xset -dpms"
exec --no-startup-id sh -c "xset s off"

# exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id blueman-applet
exec --no-startup-id nm-applet
exec --no-startup-id opensnitch-ui
exec --no-startup-id flameshot

# exec --no-startup-id xrandr --output HDMI-A-0 --right-of HDMI-A-1

# exec --no-startup-id feh --bg-scale --no-fehbg "/home/cookiengineer/Pictures/Wallpapers/neon-space.jpg"
# exec --no-startup-id feh --no-fehbg --bg-scale /home/cookiengineer/Pictures/Wallpapers/abandoned-city-1.jpg /home/cookiengineer/Pictures/Wallpapers/abandoned-city-2.jpg
# exec --no-startup-id feh --no-xinerama --bg-fill /home/cookiengineer/Pictures/Wallpapers/hongkong-skyline-01.jpg

# exec --no-startup-id i3-msg "workspace BG; exec /usr/bin/kitty"

# Fix xdg-desktop-portal with missing environment variables
exec --no-startup-id systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XAUTHORITY
exec --no-startup-id systemctl --user restart xdg-desktop-portal

